version: "3.5"
services:
  broker:
    # image: rabbitmq:3.8.2-management
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      heartbeat: 60
      # RABBITMQ_DEFAULT_USER: broker_user
      # RABBITMQ_DEFAULT_PASS: 3fZoJ1y-x5nSW_2eNx-6JBFyED2OaovX
      # RABBITMQ_ERLANG_COOKIE: "V0kS1qOsv4nnKAiHe1wiTE6kzMDNqCQO6qyRxhL2XGOgv0UhtcgrJPqjGQ"
    ports:
      - 5672:5672
      - 15672:15672

    restart: always
